#!/bin/bash

sudo chown -R mssql ./src/

nohup dotnet run -p ./src/sharpcms.web.id/project.json ./src/sharpcms.web.id/ &

nohup dotnet run -p ./src/sharpcms.web.api/project.json ./src/sharpcms.web.api/ &

nohup dotnet run -p ./src/sharpcms.web.ui/project.json ./src/sharpcms.web.ui/ &
